### ISSUE TITLE
Does not support Python 3.9

### ISSUE THREAD

**Issue by fxcoudert** [marcwebbie/passpie#122]
The pyyaml version requested does not work with Python 3.9:

```
    ext/_yaml.c:25698:26: error: no member named 'tp_print' in 'struct _typeobject'
      __pyx_type_5_yaml_Mark.tp_print = 0;
      ~~~~~~~~~~~~~~~~~~~~~~ ^
```
